# Generated by Django 3.2.10 on 2022-01-09 22:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.FileField(default='uploads/avatar/default.jpg', upload_to=users.models.user_dir_path),
        ),
    ]
