# Generated by Django 3.2.10 on 2022-01-09 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=32, verbose_name='站点标题')),
                ('site_name', models.CharField(max_length=32, verbose_name='站点名称')),
                ('site_theme', models.CharField(max_length=64, verbose_name='站点样式表')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.usersite'),
        ),
        migrations.AlterField(
            model_name='category',
            name='blog_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.usersite'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='blog_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.usersite'),
        ),
        migrations.DeleteModel(
            name='BlogSite',
        ),
    ]
