# Generated by Django 3.2.10 on 2022-01-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20220109_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_site',
            new_name='user_site',
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='site_theme',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='站点样式表'),
        ),
    ]
