# Generated by Django 3.2.10 on 2022-01-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20220112_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='blog_site',
            new_name='user_site',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='blog_site',
            new_name='user_site',
        ),
        migrations.AddField(
            model_name='blog',
            name='comment_num',
            field=models.BigIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='blog',
            name='down_num',
            field=models.BigIntegerField(default=0, verbose_name='点踩数'),
        ),
        migrations.AddField(
            model_name='blog',
            name='up_num',
            field=models.BigIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
