# Generated by Django 3.2.10 on 2022-01-13 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20220113_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='upanddown',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usersite',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.comment', verbose_name='根评论'),
        ),
    ]
