# Generated by Django 3.2.10 on 2022-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20220113_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='usersite',
            name='site_theme',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='站点样式表'),
        ),
    ]
